version: '3.8'

services:
  app:
    container_name: myapp
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=myappdb
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myappdb
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data: